services:
  hyperf:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        timezone: America/Sao_Paulo
    container_name: wallet-core-hyperf
    ports:
      - "9501:9501"
    volumes:
      - ./:/opt/www
    depends_on:
      - mysql
    command: php bin/hyperf.php server:watch
    environment:
      APP_NAME: wallet-core
      APP_ENV: dev
      SCAN_CACHEABLE: "false"
      TZ: America/Sao_Paulo
      DB_DRIVER: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: wallet-core
      DB_USERNAME: wallet-core
      DB_PASSWORD: wallet-core-secret
    networks:
      - wallet-core-network
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: wallet-core-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root-secret
      MYSQL_DATABASE: wallet-core
      MYSQL_USER: wallet-core
      MYSQL_PASSWORD: wallet-core-secret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - wallet-core-network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
    driver: local

networks:
  wallet-core-network:
    driver: bridge
